#ifndef COMMON_H
#define COMMON_H

#define DEFAULT_PORT 5555
#define BUFFER_SIZE 2048

#define CMD_SEARCH "SEARCH"
#define CMD_SEATS "SEATS"
#define CMD_CHECK_CONNECT "CHECK_CONNECT"
#define CMD_HAS_CONNECTIONS "HAS_CONNECTIONS"
#define CMD_BOOK_DIRECT "BOOK_DIRECT"
#define CMD_BOOK_CONNECT "BOOK_CONNECT"
#define CMD_QUIT "QUIT"

#endif